version: 2.1

orbs:
  docker: circleci/docker@2.8.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:21.0.5
  python-executor:
    docker:
      - image: cimg/python:3.12

jobs:
  run-core-tests:
    executor: java-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: cd core && make test

  build-example:
    executor: java-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: cd example && make build-docker githubUser=${GITHUB_USER} githubToken=${GITHUB_TOKEN}
      - run:
          name: Save Image
          command: cd example && make save-image
      - persist_to_workspace:
          root: example
          paths:
            - faas-example.tar

  run-functional-tests:
    executor: python-executor
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: leonpatmore2/spring-boot-faas
          path: core
          docker-context: core
      - run:
          name: Setup
          command: cd tests && make install
      - run:
          name: Lint
          command: cd tests && make lint
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Faas Example Image
          command: docker load --input /tmp/workspace/faas-example.tar
      - run:
          name: Run Tests
          command: cd tests && make run
          environment:
            FAAS_IMAGE_NAME: faas-example:latest
            HANDLER_PATH: ''
      - docker/push:
          image: leonpatmore2/spring-boot-faas

  push-docker-image:
    executor: docker/docker
    steps:
      - docker/push:
          image: leonpatmore2/spring-boot-faas

workflows:
  version: 2
  ci:
    jobs:
      - build-example
      - run-core-tests
      - run-functional-tests:
          requires:
            - build-example
      - push-docker-image:
          requires:
              - run-core-tests
              - run-functional-tests
